### ISSUE TITLE
Loot Bags Scattered on the Map

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#27]
We need the Loot Bags Scattered throughout the world for people to explore.

- Insert into mapbox
- Add scatterplot layer in deck.gl

**Comment by rvorias** [comment]
Added geojson to repo.
Do we want some kind of order bias? if there is an order item, also put that bag in that order?

**Comment by ponderingdemocritus** [comment]
nice

The Lore is that they are lost bags that have been rediscovered so they can be 100% random. 

GAs on the other hand should exist within their own lands.

**Comment by rvorias** [comment]
Streamlined the geodata in https://github.com/BibliothecaForAdventurers/realms-react/tree/feature/add_bags
Will have to test if everything still works as expected.

Not sure what the policy of submodules is, but it would be nice to have 1 source of truth (the world-data repo imo), then just pull in the latest changes instead of copypasting.
