### ISSUE TITLE
feat: use of the colour red in the UI - user nicabar

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#413]
UI/UX - When minting max five realms, many red-colored actions pop up with what is going on. This outcome feels jarring and too much in your face.

UI/UX - Red does not feel like the “right” color for actions that need attention (I get the reason, but the first impression is ALERT and something is WRONG)

UI/UX - Too much RED color (FYI I love the color red) If the red is a placeholder until more visual cues can be added, great, but if it's a color choice for buttons, then nope.

UI/UX - When constructing a castle, I need more clarification on how and what to do. Sign For (I) Command but can't click the button (currently, I’m being trained that red means I can click, but learning that not all red. If red is not bright red, maybe I cant click.

UI/UX - The red lines are neat, but I would like the option to turn off others. The option to filter which users to see could be interesting. I will need more context before making suggestions, but for now, toggling to see only where I am traveling and who is traveling to me would be helpful.

Again too much red, and the lines feel too strong of a stroke line. A lower alpha value and make the lines more transparent. Red lines for enemy troops coming to your castle another color for your troops traveling to a castle.

------

nicabar has a file: https://docs.google.com/document/u/0/d/1xy05Dtpyx51y99JPRjR7jRnhWNi9OSqVnJHV6SwWi4c

I will be grouping some of his feedback and putting it into feature requests.

**Comment by ponderingdemocritus** [comment]
@Amaro-Koberle thoughts?

**Comment by ponderingdemocritus** [comment]
@Amaro-Koberle

**Comment by ponderingdemocritus** [comment]
@Amaro-Koberle please add your thoughts, either make new issues about comments or close

**Comment by Amaro-Koberle** [comment]
@ponderingdemocritus So sorry, only saw this now, haven't checked my email notifications in a minute. Yes, I agree with the sentiment. Red is a tricky primary colour because it is usually used to signal alert, especially the warm shade of red that we use. It's not like you can't get away with it (Netflix and AirBnB are examples), but there are good reasons to choose something that doesn't look like an alert.

I have suggested to you in a private chat once before that we change the primary color to a green because snakes are a central part of the branding of Eternum. Here again, probably better to avoid signal green (bright and saturated) and go for something more muted (#507044 for example).

My prefered option, also mentioned before elswhere, is to consistently apply the following rule across the board in the whole atlas:
If you can click it, it's golden, if you can't click it, it's not.
![image](https://user-images.githubusercontent.com/53105057/223859396-0d74d8b2-c2e7-4b2c-855d-f52d793e5ac5.png)
Something like that. I think we can close this. Will open another issue specifically about the button colors.
