### ISSUE TITLE
feat: retry previous failed transaction - save txs in cart if failure caused by lack of $lords

### ISSUE THREAD

**Issue by gogibear** [BibliothecaForAdventurers/realms-react#449]
Pretty much title. I don't know whether this request would mean the txs won't disappear or failed txs will appear in your history and have a button to queue them up again easily. On that note would it be possible and worthwhile to be able to save favourite/commonly used lists of txs in your history to queue them up easily?

Here is a screenshot of the initial comment requesting this for additional clarity:

<img width="849" alt="ss" src="https://user-images.githubusercontent.com/102257289/218170154-09cf11b0-6f0f-4b3e-abce-29133f79226f.png">

**Comment by ponderingdemocritus** [comment]
This is possible but is quite the edge case and quite a bit of work to make it stable. Also - Argent X will be updating and will probably introduce this feature.

**Comment by Amaro-Koberle** [comment]
I think we shouldn't even ever let the player attempt a transaction if they do not have the resources for the transaction to go through. If we know for sure that the transaction will fail, never send the player to do anything at all in the wallet because it will just be a frustrating dead end.

This feature would be a patch for a problem we shouldn't be having in the first place.
