### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by Amaro-Koberle** [BibliothecaForAdventurers/realms-react#450]
The images are still WIP, but I think we can start worrying about placing the intro. The images in that folder will update as I continue to work.

I think we can do something similar to what we did for the battle scenes.

https://drive.google.com/drive/folders/1hCaMdbdu310lHbKdZL-Cu4RuwCi8uVDW

We need to discuss when to play this.

**Comment by Fomentador** [comment]
The first time someone settles a Realm the intro should play out on the screen, with the option to skip it.  Forcing the player to watch accomplishes nothing but annoyance if they don't want to.
There also should be a button in the game's landing page for the intro to be played at any time the player wants to, since the intro is about tone and immersion and players who have been inactive for a while could benefit from watching it again. Also, if people want to spend more time in Eternum watching the art, that's a positive for us.

Again, there's no rush for this. We'd only need an intro at earliest in beta, which should be a good while away yet. I wouldn't worry it right now.

**Comment by ponderingdemocritus** [comment]
closing this. Please make a specific issue later once the intro has been completed @Amaro-Koberle
