### ISSUE TITLE
feat: swap realm orders

### ISSUE THREAD

**Issue by palomato** [BibliothecaForAdventurers/realms-react#451]
_Note: this feature requires NFT traits to be editable_

Orders have potential to play a large role in the game, but how to do it when every player owns realms of multiple orders? Players should be allowed to swap their realm’s Order with another player, like an Order p2p marketplace. This way players have a way to get all of their owned realms into the same Order. Orders can develop an identity. Alliances can form, order-vs-order rivalries, etc. all because the Order trait could be swapped. It also adds an interesting dynamic to the world map.

To prevent abuse, suggest a timeout is implemented so that after swapping Orders, the realm cannot swap again for a period of time.

To help players navigate the process of swapping, a new tab could be added to the Empire page. It might look like this:

![1](https://user-images.githubusercontent.com/42439169/218305472-924f9b19-fb1e-43b1-8d6d-8e7f28a1c76e.png)

The columns of orders on the left side display existing unfilled swaps from other players. Player clicks Detection and is shown unfilled swaps from Detection to Power, Anger, Enlightenment, etc. Line width corresponds with the number of unfilled swaps available. Player selects Power and is shown all unfilled swaps from Detection to Power on the right side. Player's Power realms are automatically populated (if player owns any). In this case the player owns Oayerfhy, a Power realm. Player can selects his own realm and the desired eligible realm, which populates a swap text box below. Click swap to execute.

![2](https://user-images.githubusercontent.com/42439169/218305900-d57a70be-da25-4fd1-8651-b9739708e11f.png)

Here the player owns Lystoma, a Titans realm, and wants to swap with Detection, but there are no existing unfilled orders available. In this case player can create his own unfilled order by indicating he will swap Lystoma with Any Realm of Detection. Swap text box below is populated, click swap to execute.

![3](https://user-images.githubusercontent.com/42439169/218306032-7f516888-ce88-47a4-b26a-06dd45efea5b.png)

The player's unfilled (open) swaps appear below the swap text box, with the option to cancel.

**Comment by palomato** [comment]
Order swaps do not have to be permanent. An in-game event, epoch/Age/season, etc could trigger all realms to revert to their original Orders, resetting the map.

**Comment by ponderingdemocritus** [comment]
I like this idea - because then there is no net growth of a specific Order, it just shuffles around. This is possible already on StarkNet, we just need to enable it and build the swapping function.

**Comment by ponderingdemocritus** [comment]
this would be a nice little module to build for someone learning cairo

**Comment by Fomentador** [comment]
A big part of the options that Orders present for game design is precisely in because they're an immutable trait. We already have several modules (guilds, banners, empire) that introduce the concept of a group you can choose to participate in and present this gameplay avenue, and the game will support this and provide experiences for them. You'll be able to engage in battles and fight for Monuments only with your group, for instance, your chosen allies. So if Orders are mutable, what's the big difference between them and groups? That they're less mutable? The fact that they reset periodically wouldn't make a difference for people who hold several Realms, they can just swap them automatically again.

This touches upon another point - the average number of Realms per wallet is 6, with many players having more. If we allow Order swapping people can just consolidate their Realms around specific Orders and create an inherent resource imbalance in Orders, which means some Orders could be extremely more powerful than others. The way the contract distribution works is that Orders were more or less evenly distributed among resources. All Orders have at least one dragonhide, almost all Orders have three wonders, and so it goes. With Order swapping people will naturally flock towards the strongest Orders - this means swapping the Order of your wood and coal Realms for the Order of your Ruby Realm. Some Orders would grow powerful while others would be powerless, which just makes Order conflict way less interesting, since many would be simply one-sided. Single and few Realms players would be the most harmed, for they wouldn't have the option to trade it at their will, and would be stuck with weaker Orders. Again, resetting this periodically doesn't solve the problem since multi-Realm owners would just swap their Orders as soon as the reset happen.

The third point is that the only impact that changing your Realm would have is in how it affects the game design, right? If your Order has no impact in gameplay, then changing it is irrelevant, we could let all 8,000 Realms be the same Order. So the question we have to ask here is: does this proposal make Order gameplay more interesting and engaging for the game as a whole? Does it creates more opportunity for conflict and coordination between Orders as a whole? If we just think of specific situations where a minority of players are to benefit, it harms the game itself because then it's less fun for all the rest, and fun is king. If it isn't fun, people just don't play it. (Also, all the systems of the game are being designed under the assumption of a static Order system, I would have to change or remake all of them if we change how Orders work. )

@palomato, what do you think about these points? Do you see them as problems? Do you disagree with any of them?

**Comment by palomato** [comment]
> groups

Players can still participate in groups. Remember, players must find a counterparty to swap with. Not all will, so groups have relevance.
<br>
> resource imbalance possible

Yes that could happen, as happens IRL. Just like IRL, weaker Orders may decide to team up to counter stronger Orders. A bit of of imbalance can be exciting.
<br>
> will this proposal make gameplay more interesting?

Absolutely. Now Orders have relevance and can develop an identity. Alliances can form, order-vs-order rivalries, negotiation (bribes?) between players trying to get into an Order, new modules built around Orders, etc. All possible because the Order trait could be swapped.

The world of possibilities enabled by swapping Orders far outweighs the concerns, makes the game map 'dynamic', and encourages interaction between players.
