### ISSUE TITLE
feat: Spin out this repo into individual parts

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/realms-react#452]
As much as the mono repo was a good idea. I think it is actually a blocker for contributors to the open-source nature of this project. We are also not fully leveraging of why we did this monorepo in the first place. If this project was closed-source and managed only by 3 people, then it would be different. Our goal it to surface and make it easy for contributors.

We should spin out:

- Atlas Client
- Bibliotheca site

If we do this - individual managers can be assigned to each and can move at independent speeds. I have begun doing this in the contract repos.

We should reduce the complexity of the repo and redo the readme into a readme about what each project is - not the actual monorepo...

**Comment by RedBeardEth** [comment]
Personally I find the monorepo very easy to use - and in the future gives some advantages if we move to having SDK or component packages shared between multiple sites (for example if we split the AMM, make a separate asset viewer etc). The monorepo makes testing updates to those shared packages substantially easier (moving at independent speeds and not having a shared environment can make long term consistency and efficently substantially lower)

**Comment by ponderingdemocritus** [comment]
I disagree - we have many branches which is where we manage all the different apps in their different lifecycle. I'm unsure about the state of apps are. 

For collaboration this makes it much harder than just a main and dev branch for each app which maintainers and contributors can easily see.

If we were a small team and that was it. This would make sense, but it is too hard to own parts of a monorepo with different merge permissions.

From a bounty POV it is also messy and hard to coordinate as all the issues are bundled up into one and this problem multiplies the more apps that exist.

**Comment by RedBeardEth** [comment]
There are some simplicity benefits in decoupling - but they probably come at the expense of consistency. We are in an odd situation at the moment in that we have two "production" branches (main - with the current Atlas, and settling - with everything else) if that's what you mean by the many branches. Some advantage of the monorepo are situations where you have core react libraries, e.g SDK for AMM, used by eternum and a separate marketplace app, and you need to fix a bug in the sdk that requires updates in both frontends. If separated then you need to push fixes into production on three separate repos (which may have diverged in implementation due to different maintainers). It also provides better visibility to the entire team to changes in the codebase (which in a decentralized project may reduce security issues). 

There are definitely advantages to both implementations (and I'm not convinced one way or the other) - so would be great to get other contributors opinions

**Comment by ponderingdemocritus** [comment]
I think the SDK is the perfect example of why they should all be decoupled. After attempting to maintain this repo for the past 6 months this is a first-hand experience in both developing and PMing.

Coupling things together restricts outside collaboration which then results in slower iteration because there is a larger codebase to maintain, which equals a greater quantity of issues to track and manage. I am willing to trade off slightly slower upgradability (barely imo) for independent iteration speeds.

For example:

- Eternum Client
- DAO Site
- Eternum Landing Page
- General Realms SDK
- Component SDK

Each of these projects should have independent maintainers with independent issue lists. Right now contributors would need to:

- Navigate issues
- Clone the entire repo
- Navigate to a specific branch
- Create PR into that branch (which would be non-standard)
- Then merged up 

This just falls into the 'too hard' bucket for many contributors.

**Comment by ponderingdemocritus** [comment]
also to note - I have done this on the contracts, as have run into the exact same issue

**Comment by RedBeardEth** [comment]
The landing page probably isnt going to use the shared libraries, but the rest are fairly tightly coupled (especially in the current rapid iteration). I am somewhat scarred from previous projects that required making changes in an upstream packages and building -then updating packages of the frontend in local development everytime (e.g adding a graphql field to the realms SDK in order to fetch it in the the Eternum client)- or alternatively a fairly complex local development/docker environment. Do you know of any solutions to that (I don't believe this issue really exists at as high a velocity on the contract side)?

That process of PR could be simplified by dropping the current production atlas build from the repo (the settling branch is decoupled enough anyway that we cant really merge updates to it) - and make settling the main branch (and some Issue creation hygiene such as specifying which projects an issue relates too - which is an advantage over split repos too which may require making an issue in several repos)

**Comment by ponderingdemocritus** [comment]
I personally don't see that as a huge issue. In fact, I think strongly decoupled SDK from the clients makes much more sense as they will diverge anyway. It will foster independent client growth and improved SDK iteration. Each repo maintained should do one thing and one thing well, much like a function should.

Yes - there is upstream to pull in case of a change, but a VSC development environment could just contain the SDK repo + whatever client the user is working on - if they do want to also work on the SDK at the same time.

**Comment by RedBeardEth** [comment]
Definitely agree in somewhat stable architectures, I'm just not 100% sure we are there but only one way to find out

If you are convinced that is the best path forward - maybe first we can create the Realms SDK repo before splitting up this monorepo and get it integrated to the eternum client to ensure the developer experience is straightforward.

**Comment by ponderingdemocritus** [comment]
I am pretty convinced as then people can be assigned specific repos to manage with clear ownership.

We need to make urgent changes to the landing page and the DAO site, so these can be spun out immediately. 

For now, until we have the two new modules and we have clarity around Cairo 1, we should hold off on the SDK.

**Comment by r0man1337** [comment]
I don't have a preference in this matter, nor have I separately studied the pros and cons of different types of repositories (but I am used to using separate repositories for different projects). To take a personal example, when I decided to contribute to Realms, it was a separate repository on Nuxt, and then continued when we switched to monorepo, in both cases I did not pay much attention to it and took it for granted. I can give my personal opinion, but it won't be expert and probably subjective. I can assume that it would be easier for a new contributor to navigate separate repositories than to learn the structure of monorepo.
