### ISSUE TITLE
feat: review buttons styles across the atlas

### ISSUE THREAD

**Issue by r0man1337** [BibliothecaForAdventurers/realms-react#470]
Need to review all the main buttons on the site, and make a list of which ones should be in the primary style (yellow bg with a snake border), and which ones should be secondary (transparent with a plain yellow border).

Right now, the button styles are chosen randomly and don't reflect the importance/meaning of the button.

**Comment by Amaro-Koberle** [comment]
![image](https://user-images.githubusercontent.com/53105057/225303503-19209325-a6b3-4927-95fa-afc15e9da361.png)
This should be primary.

![image](https://user-images.githubusercontent.com/53105057/225303624-3fa4cf59-5ce9-4c30-8fd5-cef0c7564f91.png)
These should be primary if and only if the realm is starving.

![image](https://user-images.githubusercontent.com/53105057/225303790-dcfea669-f63b-49c1-8490-e509b5735acd.png)
This can be primary as there is no other clickable element on the page

![image](https://user-images.githubusercontent.com/53105057/225304428-c4247deb-5fa0-450f-98b5-14340efaf7fa.png)
I think on the armies tab of a realm, this is the button I click most often. I think it can be primary.

![image](https://user-images.githubusercontent.com/53105057/225304698-bc64df6b-91e9-4e91-886a-bb1fb797890d.png)
This should probably be primary if and only if the mine is idle.

![image](https://user-images.githubusercontent.com/53105057/225304874-d52f3496-3f8c-495a-8ed9-78315419e424.png)
This should probably be primary if and only if there is something to harvest.

I think that is it for now.

**Comment by Amaro-Koberle** [comment]
I probably haven't found everything, will keep an eye out. But I think that is most of it.

Oh wait, never mind:
![image](https://user-images.githubusercontent.com/53105057/225305639-bfdec853-8b06-4773-8b6e-b98c40035803.png)
If there are deficits, this one should be primary.

![image](https://user-images.githubusercontent.com/53105057/225305777-8d6d21ed-f8fc-4c3a-bc0b-4e45f5359365.png)
In this case, where I have resource deficits, this should certainly not be primary. Infact, it shouldn't even be gold. Can we make the disabled version of the button look like it's a secondary button but where the gold as well as the text are just the regular paper-beige color?

While we are at it, can you change the mouse-hover effect orange rather than red? Something like hex-color #fc9323. Also, the labels of the buttons should be golden, not white, I think.

**Comment by r0man1337** [comment]
done in #478
